### ISSUE TITLE
Python 3.6

### ISSUE THREAD

**Issue by haz** [cptpcrd/pypsutil#1]
Any chance we could get this targeting 3.6 as well? Trying to swap out psutil for pypsutil, but it's on a project that is aiming to support 3.6+ and not just 3.7+.

**Comment by cptpcrd** [comment]
> Any chance we could get this targeting 3.6 as well? Trying to swap out psutil for pypsutil, but it's on a project that is aiming to support 3.6+ and not just 3.7+.

I see the linked issue seems to have been resolved separately, but since it turned out to be fairly trivial I've added 3.6 support anyway in 61ce712c7e479f0c4f1b92538c65c67cd22652e7.

**Comment by haz** [comment]
Thanks! Noticed the CI/CD focuses mainly on ubuntu/mac/freebsd. Does this work on windows natively?

**Comment by haz** [comment]
Also, curious if this will automatically trigger a version bump to pypi. Been monitoring [[this](https://pypi.org/project/pypsutil/#history)] so far.

**Comment by cptpcrd** [comment]
> Thanks! Noticed the CI/CD focuses mainly on ubuntu/mac/freebsd. Does this work on windows natively?

No. There's a list of supported platforms in the [documentation](https://pypsutil.readthedocs.io/en/latest/?badge=latest#platform-support), and lack of Windows support is also listed in the [comparison to `psutil`](https://pypsutil.readthedocs.io/en/latest/?badge=latest#pypsutil-vs-psutil).

I've got preliminary Windows support in the [`windows`](https://github.com/cptpcrd/pypsutil/tree/windows) branch, but it's incomplete. `pypsutil` was really on built to work on \*nix, and it would take a while to get Windows support working properly.

**Comment by haz** [comment]
Ah, shoot missed that doc description entirely. Thanks for the pointer!

**Comment by cptpcrd** [comment]
> Also, curious if this will automatically trigger a version bump to pypi. Been monitoring [[this](https://pypi.org/project/pypsutil/#history)] so far.

No, it won't. I've made a lot of changes since v0.1.0, and I've been planning on releasing a v0.2.0 soon, but that needs to be done manually.
